name: Node.js CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        working-directory: ./backend
        run: npm run test
